# Generated by Django 3.1.7 on 2021-02-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.PositiveSmallIntegerField(null=True)),
                ('question', models.CharField(max_length=500, null=True)),
                ('answer', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyLaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.PositiveSmallIntegerField(null=True)),
                ('question', models.CharField(max_length=500, null=True)),
                ('answer', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAccounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.PositiveSmallIntegerField(null=True)),
                ('question', models.CharField(max_length=500, null=True)),
                ('answer', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementAccounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.PositiveSmallIntegerField(null=True)),
                ('question', models.CharField(max_length=500, null=True)),
                ('answer', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetailMarketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.PositiveSmallIntegerField(null=True)),
                ('question', models.CharField(max_length=500, null=True)),
                ('answer', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMarketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.PositiveSmallIntegerField(null=True)),
                ('question', models.CharField(max_length=500, null=True)),
                ('answer', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
